CChen=mpicc
CCmac=/usr/local/bin/gcc-7
CFLAGShen=-Wall -fopenmp -lgsl -O3
CFLAGSmac=-Wall -fopenmp -lgsl -O3
EXE=jmmOneDMC

henry2 : 
	${CChen} ${CFLAGShen} Main.c -o ./${EXE}

macbook :
	${CCmac} ${CFLAGSmac} Main.c -o ./${EXE}



